services:

  # A backend which provides basic authentication and CRUD access to the Postgress DB from the client
  backend-api:
    build:
      context: ../attendee-list-backend
    environment:
      DATABASE_TYPE: ${BACKEND_DATABASE_TYPE}
      DATABASE_URI: ${BACKEND_DATABASE_URI}
      # From the PowerSync service name
      # This is just used to populate the JWT audience
      POWERSYNC_URL: http://localhost:8080

      # Keys here for demonstration
      POWERSYNC_PUBLIC_KEY: ${JWKS_PUBLIC_KEY}
      POWERSYNC_PRIVATE_KEY: ${JWKS_PRIVATE_KEY}
      JWT_ISSUER: powersync-dev

      PORT: ${BACKEND_PORT}
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
